'use client'

import { useEffect, useState } from 'react'
import { useParams } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'

export default function PrintPage() {
  const params = useParams()
  const supabase = createClient()
  
  const [data, setData] = useState<any>(null)
  const [settings, setSettings] = useState<any>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    const fetchAllData = async () => {
      const type = params.type 
      const id = params.id

      // 1. Fetch System Settings (Clinic Identity)
      const { data: settingsData } = await supabase
        .from('system_settings')
        .select('*')
        .eq('id', 1)
        .single()
      setSettings(settingsData)

      // 2. Fetch specific Record Data
      if (type === 'receipt') {
        const { data } = await supabase
          .from('invoices')
          .select('*, patients(*)')
          .eq('id', id)
          .single()
        setData(data)
      } else if (type === 'report') {
        const { data } = await supabase
          .from('consultations')
          .select('*, patients(*)')
          .eq('id', id)
          .single()
        setData(data)
      }
      setLoading(false)
    }

    fetchAllData()
  }, [params.id, params.type])

  // Trigger print and close window
  useEffect(() => {
    if (!loading && data && settings) {
      setTimeout(() => {
        window.print()
        // window.close() // Uncomment this for production to close tab after print
      }, 800)
    }
  }, [loading, data, settings])

  if (loading) return <p className="p-10 text-center animate-pulse">Fetching records...</p>
  if (!data || !settings) return <p className="p-10 text-center text-red-500">Document generation failed.</p>

  return (
    <div className="p-4 bg-white min-h-screen text-black font-mono">
      {/* --------------------------- */}
      {/* DYNAMIC RECEIPT LAYOUT      */}
      {/* --------------------------- */}
      {params.type === 'receipt' && (
        <div className="max-w-[80mm] mx-auto text-sm border-t-2 border-black pt-4">
          <div className="text-center mb-4">
            <h1 className="text-lg font-bold uppercase">{settings.hospital_name}</h1>
            <p className="text-[10px] uppercase">{settings.address}</p>
            <p className="text-[10px]">Tel: {settings.phone}</p>
            <div className="border-b border-black my-2"></div>
            <p className="text-xs">RECEIPT: {data.id.slice(0, 8).toUpperCase()}</p>
            <p className="text-[10px]">{new Date(data.created_at).toLocaleString()}</p>
          </div>

          <div className="mb-4 text-xs">
            <p><strong>PATIENT:</strong> {data.patients.first_name} {data.patients.last_name}</p>
            <p><strong>NIDA:</strong> {data.patients.nida_number}</p>
          </div>

          <div className="flex justify-between mb-4 border-y border-dashed py-2">
            <span className="uppercase">{data.description}</span>
            <span className="font-bold">{Number(data.amount).toLocaleString()} {settings.currency}</span>
          </div>

          <div className="text-center text-[10px] mt-6">
            <p>Paid via: {data.payment_method?.toUpperCase()}</p>
            <p className="mt-2 font-bold italic">Asante kwa kutuchagua.</p>
            <p>Generated by AfyaOS Core</p>
          </div>
        </div>
      )}

      {/* --------------------------- */}
      {/* DYNAMIC MEDICAL REPORT      */}
      {/* --------------------------- */}
      {params.type === 'report' && (
        <div className="max-w-3xl mx-auto font-serif p-8 border">
          <div className="flex justify-between items-center border-b-4 border-blue-800 pb-4 mb-8">
            <div className="text-left">
              <h1 className="text-2xl font-black text-blue-900 uppercase">{settings.hospital_name}</h1>
              <p className="text-xs text-gray-600">{settings.address}</p>
              <p className="text-xs text-gray-600">Email: {settings.email} | Tel: {settings.phone}</p>
            </div>
            <div className="text-right">
              <div className="bg-blue-900 text-white px-3 py-1 text-xs font-bold mb-1">MEDICAL REPORT</div>
              <p className="text-[10px] text-gray-400">Date: {new Date(data.created_at).toLocaleDateString()}</p>
            </div>
          </div>
          
          <div className="grid grid-cols-2 gap-y-2 gap-x-12 mb-8 text-sm bg-gray-50 p-4 rounded">
            <p><strong>Patient:</strong> {data.patients.first_name} {data.patients.last_name}</p>
            <p><strong>Gender:</strong> {data.patients.gender}</p>
            <p><strong>Phone:</strong> {data.patients.phone_number}</p>
            <p><strong>NIDA Number:</strong> {data.patients.nida_number}</p>
          </div>

          <div className="space-y-8">
            <section>
              <h3 className="font-bold text-xs uppercase text-blue-800 border-b mb-2">Clinical Presentation</h3>
              <p className="text-sm leading-relaxed">{data.chief_complaint}</p>
            </section>

            <section>
              <h3 className="font-bold text-xs uppercase text-blue-800 border-b mb-2">Medical Diagnosis</h3>
              <p className="text-md font-bold text-gray-900">{data.diagnosis || 'Clinical evaluation pending'}</p>
            </section>

            <section className="bg-blue-50/30 p-4 rounded-lg border border-blue-100">
              <h3 className="font-bold text-xs uppercase text-blue-800 border-b border-blue-200 mb-2">Prescription & Management Plan</h3>
              <p className="text-sm italic whitespace-pre-wrap leading-6">{data.prescription}</p>
            </section>
          </div>

          <div className="mt-24 flex justify-between">
            <div className="text-center">
              <div className="border-t border-black w-48 mb-1"></div>
              <p className="text-[10px] uppercase font-bold text-gray-500">Medical Officer Signature</p>
            </div>
            <div className="text-center">
              <div className="border border-gray-200 w-32 h-32 flex items-center justify-center text-[10px] text-gray-300 italic mb-1">
                Hospital Stamp Area
              </div>
            </div>
          </div>
          
          <div className="mt-12 text-[9px] text-gray-400 text-center border-t pt-4">
            This document is electronically generated by {settings.hospital_name} via AfyaOS Health Information System.
          </div>
        </div>
      )}
    </div>
  )
}